# Generated by Django 2.1.5 on 2019-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20190217_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
