# Generated by Django 2.1.5 on 2019-02-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='event.Event'),
        ),
    ]
