# Generated by Django 2.1.5 on 2019-03-02 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20190226_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='started_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
