# Generated by Django 2.1.5 on 2019-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0005_municipality_type'),
        ('alert', '0005_alert_started_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='federal.Ward'),
        ),
    ]
