# Generated by Django 2.1.5 on 2019-04-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_auto_20190404_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='hazard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard.Hazard'),
        ),
    ]
