# Generated by Django 2.1.5 on 2019-04-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_auto_20190411_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='hazard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard.Hazard'),
        ),
    ]
