# Generated by Django 2.1.5 on 2019-04-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_auto_20190416_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='hazard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard.Hazard'),
        ),
    ]
