# Generated by Django 2.1.5 on 2019-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_auto_20190416_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='reference_type',
            field=models.CharField(blank=True, default=None, editable=False, max_length=25, null=True),
        ),
    ]
