# Generated by Django 2.1.5 on 2019-04-19 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loss', '0015_auto_20190419_0940'),
        ('incident', '0017_auto_20190419_0541'),
        ('organization', '0002_auto_20190221_1659'),
        ('federal', '0007_auto_20190418_0213'),
        ('event', '0007_auto_20190416_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('inflow', 'Inflow'), ('initial balance', 'Initial Balance')], max_length=25)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='event.Event')),
                ('fiscal_year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='relief.FiscalYear')),
                ('provider_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_flows', to='organization.Organization')),
                ('receiver_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_flows', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('beneficiary_other', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_releases', to='loss.People')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realeases', to='incident.Incident')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realeases', to='loss.People')),
                ('provider_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_realeases', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ReleaseStatus',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='relief.ReleaseStatus'),
        ),
        migrations.AddField(
            model_name='release',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federal.Ward'),
        ),
    ]
