# Generated by Django 2.1.5 on 2019-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='provider_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_flows', to='organization.Organization'),
        ),
    ]
