# Generated by Django 2.1.5 on 2019-04-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0002_auto_20190424_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='provider_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_flows', to='organization.Organization'),
        ),
    ]
