version: '3'

services:
  server:
    image: registry.gitlab.com/bipad/server:latest
    build: .
    env_file: .env
    ports:
      - "8004:8004"
    external_links:
     - redis
     - psql-11:db
    volumes:
      - ./static:/code/static
      - ./media:/code/media
