version: '3'

services:
  server:
    env_file: .env
    build:
      context: ./docker
      dockerfile: Dockerfile.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    external_links:
     - redis
     - psql-11:db
