# Generated by Django 2.1.5 on 2019-04-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190221_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='ward',
            new_name='wards',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ward',
            new_name='wards',
        ),
        migrations.AddField(
            model_name='organization',
            name='responsible_for',
            field=models.ManyToManyField(related_name='organizations', to='organization.Responsibility'),
        ),
    ]
