# Generated by Django 2.1.5 on 2019-05-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190424_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'Responsibilities'},
        ),
    ]
