# Generated by Django 2.1.5 on 2019-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190509_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='responsible_for',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organization.Responsibility'),
        ),
    ]
