# Generated by Django 2.1.5 on 2019-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0004_hazard_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='hazard',
            name='order',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
