# Generated by Django 2.1.5 on 2019-04-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0005_auto_20190326_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='type',
            field=models.CharField(blank=True, choices=[('non_natural', 'Non Natural'), ('natural', 'Natural')], default=None, max_length=25, null=True),
        ),
    ]
