# Generated by Django 2.1.5 on 2019-04-11 05:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0006_hazard_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ('order',), 'verbose_name': 'Hazard', 'verbose_name_plural': 'Hazards'},
        ),
        migrations.AddField(
            model_name='hazard',
            name='title_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='title_ne',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='order',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='resources',
            field=models.ManyToManyField(through='hazard.HazardResources', to='contenttypes.ContentType', verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='type',
            field=models.CharField(blank=True, choices=[('non_natural', 'Non Natural'), ('natural', 'Natural')], default=None, max_length=25, null=True, verbose_name='Type'),
        ),
    ]
