# Generated by Django 2.1.5 on 2019-04-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0007_auto_20190411_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='hazard',
            name='title_ne',
        ),
    ]
