# Generated by Django 2.1.5 on 2019-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0008_auto_20190411_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='title_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='title_ne',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Title'),
        ),
    ]
