# Generated by Django 2.1.5 on 2019-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0009_auto_20190412_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='type',
            field=models.CharField(blank=True, choices=[('non natural', 'Non Natural'), ('natural', 'Natural')], default=None, max_length=25, null=True, verbose_name='Type'),
        ),
    ]
