# Generated by Django 2.1.5 on 2019-04-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0010_auto_20190419_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='icon',
        ),
        migrations.AddField(
            model_name='hazard',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True,
                                   upload_to='hazard-icons/', verbose_name='Icon'),
        ),
    ]
