# Generated by Django 2.1.5 on 2019-04-21 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0011_auto_20190421_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hazard-icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon'),
        ),
    ]
