# Generated by Django 2.1.5 on 2019-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='region',
            field=models.CharField(blank=True, choices=[('municipality', 'Municipality'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default='national', max_length=25, null=True),
        ),
    ]
