# Generated by Django 2.1.5 on 2019-02-26 05:35

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('basin', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('averages', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('station_series_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('basin', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('water_level_value', models.FloatField(blank=True, null=True)),
                ('water_level_datetime', models.DateTimeField(blank=True, null=True)),
                ('danger_level', models.FloatField(blank=True, null=True)),
                ('warning_level', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('steady', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('station_series_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
