# Generated by Django 2.1.5 on 2019-03-11 06:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('realtime', '0003_auto_20190303_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('scan', models.FloatField(blank=True, default=None, null=True)),
                ('event_on', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('brightness', models.FloatField(blank=True, default=None, null=True)),
                ('confidence', models.FloatField(blank=True, default=None, null=True)),
                ('land_cover', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                },
            ),
        ]

