# Generated by Django 2.1.5 on 2019-03-28 06:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_pollution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('minimum_temp', models.FloatField(blank=True, default=None, null=True)),
                ('maximum_temp', models.FloatField(blank=True, default=None, null=True)),
                ('current_temp', models.FloatField(blank=True, default=None, null=True)),
                ('sunrise', models.TimeField(blank=True, default=None, null=True)),
                ('sunset', models.TimeField(blank=True, default=None, null=True)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('rainfall', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
