# Generated by Django 2.1.5 on 2019-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0005_auto_20190306_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='layertable',
            name='upload_type',
            field=models.CharField(choices=[('csv', 'Csv'), ('shapefile', 'Shapefile'), ('geojson', 'Geojson'), ('geoserver', 'Geoserver')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='layertable',
            name='hazard',
            field=models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('light', 'Lightening'), ('lights', 'Lightenings')], default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='layertable',
            name='layer_type',
            field=models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='layertable',
            name='visibility_level',
            field=models.CharField(choices=[('national', 'National'), ('local', 'Local Government')], default=None, max_length=250),
        ),
    ]
