# Generated by Django 2.1.5 on 2019-03-07 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0007_auto_20190307_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layertable',
            name='hazard',
            field=models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('light', 'Lightening'), ('lights', 'Lightenings')], max_length=35),
        ),
        migrations.AlterField(
            model_name='layertable',
            name='layer_type',
            field=models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layertable',
            name='upload_type',
            field=models.CharField(choices=[('csv', 'Csv'), ('shapefile', 'Shapefile'), ('geojson', 'Geojson'), ('geoserver', 'Geoserver')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layertable',
            name='visibility_level',
            field=models.CharField(choices=[('national', 'National'), ('local', 'Local Government')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
