# Generated by Django 2.1.5 on 2019-03-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0008_auto_20190307_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layertable',
            name='hazard',
        ),
        migrations.RemoveField(
            model_name='layertable',
            name='layer_type',
        ),
        migrations.RemoveField(
            model_name='layertable',
            name='upload_type',
        ),
        migrations.RemoveField(
            model_name='layertable',
            name='visibility_level',
        ),
    ]
