# Generated by Django 2.1.5 on 2019-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0009_auto_20190307_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='layertable',
            name='hazard',
            field=models.CharField(blank=True, choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('light', 'Lightening'), ('lights', 'Lightenings')], default=None, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='layertable',
            name='layer_type',
            field=models.CharField(blank=True, choices=[('vector', 'Vector'), ('raster', 'Raster')], default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='layertable',
            name='upload_type',
            field=models.CharField(blank=True, choices=[('csv', 'Csv'), ('shapefile', 'Shapefile'), ('geojson', 'Geojson'), ('geoserver', 'Geoserver')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='layertable',
            name='visibility_level',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('local', 'Local Government')], default=None, max_length=250, null=True),
        ),
    ]
