# Generated by Django 2.1.5 on 2019-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0010_auto_20190307_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layertable',
            name='layer_cat',
            field=models.CharField(blank=True, choices=[('hazard', 'Hazard'), ('vulnerability', 'Vulnerability'), ('resource', 'Capacity & Resources'), ('exposure', 'Exposure')], default=None, max_length=250, null=True),
        ),
    ]
