# Generated by Django 2.1.5 on 2019-03-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0005_auto_20190306_1723'),
        ('risk_profile', '0010_auto_20190307_0817'),
    ]

    operations = [
    ]
