# Generated by Django 2.1.5 on 2019-03-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0011_merge_20190307_0905'),
        ('risk_profile', '0011_auto_20190307_0928'),
    ]

    operations = [
    ]
