# Generated by Django 2.1.5 on 2019-03-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0015_policestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='district',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='district',
        ),
    ]
