# Generated by Django 2.1.5 on 2019-03-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0012_merge_20190307_0935'),
        ('risk_profile', '0016_auto_20190307_1053'),
    ]

    operations = [
    ]
