# Generated by Django 2.1.5 on 2019-03-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0018_auto_20190307_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='address',
        ),
    ]
