# Generated by Django 2.1.5 on 2019-03-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0017_merge_20190307_1109'),
        ('risk_profile', '0019_remove_education_address'),
    ]

    operations = [
    ]
