# Generated by Django 2.1.5 on 2019-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0020_merge_20190308_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='the_geom',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='layertable',
            name='hazard',
            field=models.CharField(blank=True, choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('light', 'Lightening'), ('lights', 'Lightenings')], default=None, max_length=35, null=True),
        ),
    ]
