# Generated by Django 2.1.5 on 2019-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0021_auto_20190308_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='the_geom',
        ),
        migrations.RemoveField(
            model_name='layertable',
            name='hazard',
        ),
        migrations.AddField(
            model_name='layertable',
            name='input',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
