# Generated by Django 2.1.5 on 2019-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0026_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=50, null=True),
        ),
    ]
