# Generated by Django 2.1.5 on 2019-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0027_auto_20190324_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community')], default=None, max_length=50, null=True),
        ),
    ]
