# Generated by Django 2.1.5 on 2019-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0028_auto_20190324_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
    ]
