# Generated by Django 2.1.5 on 2019-03-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0029_health_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Comments',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='number_of_employees',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='number_of_students',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='opening_hours',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community'), ('other', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
