# Generated by Django 2.1.5 on 2019-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0030_auto_20190324_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='Comments',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='atm_available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('development', 'Development'), ('finance', 'Finance'), ('micro_credit_development', 'Micro Credit Development')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='opening_hours',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community'), ('other', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
    ]
