# Generated by Django 2.1.5 on 2019-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0031_auto_20190325_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='ambulance_service',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='emergency_service',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='icu',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='nicu',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='operating_theatre',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='x_ray',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
    ]
