# Generated by Django 2.1.5 on 2019-03-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0032_auto_20190325_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Comments',
            new_name='comments',
        ),
    ]
