# Generated by Django 2.1.5 on 2019-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0034_auto_20190325_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='ambulance_service',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='icu',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='nicu',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='operating_theatre',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='x_ray',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
    ]
