# Generated by Django 2.1.5 on 2019-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0035_auto_20190325_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='emergency_service',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='operating_theatre',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
