# Generated by Django 2.1.5 on 2019-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0036_auto_20190325_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioEconomicGapanapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('gn_type', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('province', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('no_facility_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('one_atleast_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('radio_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('television_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cablet_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('computer_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('internet_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('telegraph_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mobile_com', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('wood_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('kerosene_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('lpgas_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('biogas_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('sa_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('electricity_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('other_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('nosta_cook', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('electricity_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('kerosene_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('biogas_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('solar_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('other_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('nons_light', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('tap_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('tube_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cok_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('unco_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('spou_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('river_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('other_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('nots_water', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('wit_toilet', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('flush_toilet', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('ordinary_toilet', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('not_toilet', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
