# Generated by Django 2.1.5 on 2019-04-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0037_socioeconomicgapanapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, default=None, max_length=550, null=True)),
                ('remoteness', models.CharField(blank=True, default=None, max_length=550, null=True)),
                ('hdi', models.CharField(blank=True, default=None, max_length=550, null=True)),
                ('riskScore', models.CharField(blank=True, default=None, max_length=550, null=True)),
            ],
        ),
    ]
