# Generated by Django 2.1.5 on 2019-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0038_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
