# Generated by Django 2.1.5 on 2019-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0040_auto_20190409_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='biogas_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='biogas_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='cablet_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='cok_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='computer_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='electricity_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='electricity_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='flush_toilet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='internet_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='kerosene_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='kerosene_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='lpgas_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='mobile_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='no_facility_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='nons_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='nosta_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='not_toilet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='nots_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='one_atleast_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='ordinary_toilet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='other_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='other_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='other_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='radio_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='river_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='sa_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='solar_light',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='spou_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='tap_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='telegraph_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='television_com',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='tube_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='unco_water',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='wit_toilet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicgapanapa',
            name='wood_cook',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
