# Generated by Django 2.1.5 on 2019-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0042_auto_20190410_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='district_id',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='province_id',
            field=models.CharField(blank=True, default=None, max_length=550, null=True),
        ),
    ]
