# Generated by Django 2.1.5 on 2019-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0043_auto_20190418_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socioeconomicgapanapa',
            old_name='telegraph_com',
            new_name='telephone_com',
        ),
        migrations.AddField(
            model_name='socioeconomicgapanapa',
            name='district_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomicgapanapa',
            name='municipality_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomicgapanapa',
            name='province_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
