# Generated by Django 2.1.5 on 2019-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0044_auto_20190418_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='human_poverty_index',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='life_expectancy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='per_capita_income',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
