# Generated by Django 2.1.5 on 2019-05-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0045_auto_20190510_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='human_poverty_index',
            new_name='humanPovertyIndex',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='life_expectancy',
            new_name='lifeExpectancy',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='per_capita_income',
            new_name='perCapitaIncome',
        ),
    ]
