# Generated by Django 2.1.5 on 2019-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0046_auto_20190510_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'health_views',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Bridge',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='MarketCenter',
        ),
        migrations.DeleteModel(
            name='Policestation',
        ),
        migrations.DeleteModel(
            name='Settlements',
        ),
    ]
