# Generated by Django 2.1.5 on 2019-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0048_hydropower'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hydropower',
            name='gapanapa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hydropower',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
