# Generated by Django 2.1.5 on 2019-05-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0049_auto_20190520_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood_basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flood_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePeriod', models.CharField(blank=True, max_length=50, null=True)),
                ('floodBasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_profile.Flood_basin')),
            ],
        ),
    ]
