# Generated by Django 2.1.5 on 2019-05-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0051_auto_20190521_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPeriodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnperiod', models.CharField(blank=True, max_length=50, null=True)),
                ('workspace', models.CharField(blank=True, max_length=50, null=True)),
                ('timePeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_profile.FloodPeriod')),
            ],
        ),
    ]
