# Generated by Django 2.1.5 on 2019-05-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0053_auto_20190521_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='floodperiod',
            name='floodBasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floodperiod', to='risk_profile.FloodBasin'),
        ),
        migrations.AddField(
            model_name='floodbasin',
            name='hazardType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floodbasin', to='risk_profile.HazardType'),
        ),
    ]
