# Generated by Django 2.1.5 on 2019-05-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0054_auto_20190521_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('hazardType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HazardType', to='risk_profile.HazardType')),
            ],
        ),
        migrations.CreateModel(
            name='HazardSubLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazardSubLayer', models.CharField(blank=True, max_length=50, null=True)),
                ('hazardLayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HazardSubLayer', to='risk_profile.HazardLayer')),
            ],
        ),
        migrations.CreateModel(
            name='HazardSubLayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnperiod', models.CharField(blank=True, max_length=50, null=True)),
                ('workspace', models.CharField(blank=True, max_length=50, null=True)),
                ('hazardSubLayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HazardSubLayerDetail', to='risk_profile.HazardSubLayer')),
            ],
        ),
        migrations.RemoveField(
            model_name='floodbasin',
            name='hazardType',
        ),
        migrations.RemoveField(
            model_name='floodperiod',
            name='floodBasin',
        ),
        migrations.RemoveField(
            model_name='floodperioddetail',
            name='timePeriod',
        ),
        migrations.DeleteModel(
            name='FloodBasin',
        ),
        migrations.DeleteModel(
            name='FloodPeriod',
        ),
        migrations.DeleteModel(
            name='FloodPeriodDetail',
        ),
    ]
