# Generated by Django 2.1.5 on 2019-05-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0055_auto_20190522_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardlayer',
            name='hazardType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HazardLayer', to='risk_profile.HazardType'),
        ),
    ]
