# Generated by Django 2.1.5 on 2019-05-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0056_auto_20190522_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardlayer',
            old_name='hazardType',
            new_name='hazard_type',
        ),
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='hazardLayer',
            new_name='hazard_layer',
        ),
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='hazardSubLayer',
            new_name='hazard_subLayer',
        ),
        migrations.RenameField(
            model_name='hazardsublayerdetail',
            old_name='hazardSubLayer',
            new_name='hazard_subLayer',
        ),
    ]
