# Generated by Django 2.1.5 on 2019-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0058_auto_20190522_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydropower',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='hydropower',
            old_name='project',
            new_name='name',
        ),
    ]
