# Generated by Django 2.1.5 on 2019-05-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0059_auto_20190526_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExposureLayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('workspace', models.CharField(blank=True, max_length=50, null=True)),
                ('layername', models.CharField(blank=True, max_length=50, null=True)),
                ('center', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_subLayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExposureLayerDetail', to='risk_profile.ExposureLayer')),
            ],
        ),
        migrations.CreateModel(
            name='ExposureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='exposure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExposureLayer', to='risk_profile.ExposureType'),
        ),
    ]
