# Generated by Django 2.1.5 on 2019-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0060_auto_20190527_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardsublayer',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='layername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='workspace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
