# Generated by Django 2.1.5 on 2019-05-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0061_auto_20190527_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardsublayerdetail',
            name='hazard_subLayer',
        ),
        migrations.DeleteModel(
            name='HazardSubLayerDetail',
        ),
    ]
