# Generated by Django 2.1.5 on 2019-05-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0062_auto_20190527_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposurelayerdetail',
            name='exposure_subLayer',
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='layername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='workspace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ExposureLayerDetail',
        ),
    ]
