# Generated by Django 2.1.5 on 2019-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0063_auto_20190528_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposurelayer',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
