# Generated by Django 2.1.5 on 2019-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0064_auto_20190604_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposurelayer',
            old_name='url',
            new_name='geoserver_url',
        ),
        migrations.RenameField(
            model_name='exposurelayer',
            old_name='workspace',
            new_name='geoserver_workspace',
        ),
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='hazard_subLayer',
            new_name='geo_workspace',
        ),
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='url',
            new_name='geoserver_url',
        ),
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='workspace',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='exposurelayer',
            name='center',
        ),
        migrations.RemoveField(
            model_name='hazardsublayer',
            name='center',
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='is_geoserver',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardtype',
            name='hazard_icon',
            field=models.CharField(blank=True, choices=[('hazard', 'Hazard'), ('vulnerability', 'Vulnerability'), ('resource', 'Capacity & Resources'), ('exposure', 'Exposure')], default=None, max_length=250, null=True),
        ),
    ]
