# Generated by Django 2.1.5 on 2019-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0065_auto_20190605_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardsublayer',
            old_name='geo_workspace',
            new_name='geoserver_workspace',
        ),
    ]
