# Generated by Django 2.1.5 on 2019-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0069_auto_20190605_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposurelayer',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='visibility_level',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('local', 'Local Government')], default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='visibility_level',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('local', 'Local Government')], default=None, max_length=250, null=True),
        ),
    ]
