# Generated by Django 2.1.5 on 2019-06-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0070_auto_20190605_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposurelayer',
            name='public',
        ),
        migrations.RemoveField(
            model_name='exposurelayer',
            name='visibility_level',
        ),
        migrations.RemoveField(
            model_name='hazardsublayer',
            name='public',
        ),
        migrations.RemoveField(
            model_name='hazardsublayer',
            name='visibility_level',
        ),
    ]
