# Generated by Django 2.1.5 on 2019-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0071_auto_20190605_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layertable',
            name='layer_type',
        ),
        migrations.RemoveField(
            model_name='layertable',
            name='visibility_level',
        ),
        migrations.AddField(
            model_name='exposurelayer',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardsublayer',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
