# Generated by Django 2.1.5 on 2019-06-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0072_auto_20190605_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayerTable',
            new_name='CapacityResources',
        ),
    ]
