# Generated by Django 2.1.5 on 2019-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0073_auto_20190606_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardtype',
            name='hazard_icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
