# Generated by Django 2.1.5 on 2019-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0074_auto_20190701_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacityresources',
            name='filter_range',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
