FROM python:3.6-alpine

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code/docker
WORKDIR /code

RUN \
  apk add --no-cache \
  musl-dev \
  gcc \
  postgresql-dev && \
  apk add --no-cache \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  openssl \
  gdal-dev \
  geos-dev \
  proj4-dev \
  zlib-dev \
  jpeg-dev

ENTRYPOINT /code/docker/docker-entrypoint.local.sh
