# Generated by Django 2.1.5 on 2019-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('catastrophic', 'Catastrophic')], default=None, max_length=25, null=True),
        ),
    ]
