# Generated by Django 2.1.5 on 2019-04-16 02:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190411_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='event',
            name='started_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
