# Generated by Django 2.1.5 on 2019-04-16 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190416_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ended_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ended on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Started on'),
        ),
    ]
