# Generated by Django 2.1.5 on 2019-04-16 09:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190416_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326, verbose_name='Polygon'),
        ),
    ]
