# Generated by Django 2.1.5 on 2019-04-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0010_auto_20190419_0541'),
        ('event', '0007_auto_20190416_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hazard',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='hazard.Hazard', verbose_name='Hazard'),
        ),
    ]
