# Generated by Django 2.1.5 on 2019-02-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0002_auto_20190224_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestocks', to='loss.LivestockType'),
        ),
    ]
