# Generated by Django 2.1.5 on 2019-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0003_auto_20190226_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='estimated_loss',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
