# Generated by Django 2.1.5 on 2019-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0004_auto_20190325_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('affected', 'Affected'), ('relocated', 'Relocated'), ('evacuated', 'Evacuated')], max_length=25),
        ),
    ]
