# Generated by Django 2.1.5 on 2019-03-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0005_auto_20190326_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='economic_loss',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='economic_loss',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
