# Generated by Django 2.1.5 on 2019-04-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20190311_0652'),
        ('loss', '0006_auto_20190327_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
