# Generated by Django 2.1.5 on 2019-04-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0008_auto_20190411_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'verbose_name': 'Infrastructure', 'verbose_name_plural': 'Infrastructures'},
        ),
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name': 'Livestock', 'verbose_name_plural': 'Livestocks'},
        ),
        migrations.AlterModelOptions(
            name='loss',
            options={'verbose_name': 'Loss', 'verbose_name_plural': 'Losses'},
        ),
    ]
