# Generated by Django 2.1.5 on 2019-04-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0011_infrastructure_beneficiary_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ne', models.CharField(max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='disabled',
        ),
        migrations.AlterField(
            model_name='people',
            name='loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='loss.Loss'),
        ),
        migrations.AddField(
            model_name='people',
            name='disability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='loss.DisabilityType', verbose_name='Disability'),
        ),
    ]
