# Generated by Django 2.1.5 on 2019-04-19 09:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0013_auto_20190419_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('beneficiary_owner', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Beneficiary Owner')),
                ('beneficiary_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Beneficiary Count')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultures', to='loss.Loss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgricultureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='loss.AgricultureType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agriculture',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agricultures', to='loss.AgricultureType', verbose_name='Type'),
        ),
    ]
