# Generated by Django 2.1.5 on 2019-04-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0014_auto_20190419_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='loss.InfrastructureUnit', verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
