# Generated by Django 2.1.5 on 2019-04-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0015_auto_20190419_0935'),
        ('loss', '0015_auto_20190419_0940'),
    ]

    operations = [
    ]
