# Generated by Django 2.1.5 on 2019-04-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0017_auto_20190419_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriculture',
            options={'verbose_name': 'Agriculture', 'verbose_name_plural': 'Agriculture'},
        ),
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Infrastructure Title'),
        ),
        migrations.AlterField(
            model_name='people',
            name='disability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='loss.DisabilityType', verbose_name='DISABILITY'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=None, max_length=25, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='loss.Country', verbose_name='Nationality'),
        ),
    ]
