# Generated by Django 2.1.5 on 2019-04-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0007_auto_20190418_0213'),
        ('loss', '0018_auto_20190421_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='address',
        ),
        migrations.RemoveField(
            model_name='people',
            name='address',
        ),
        migrations.AddField(
            model_name='family',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='federal.Ward', verbose_name='Ward'),
        ),
        migrations.AddField(
            model_name='people',
            name='ward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='federal.Ward', verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='people',
            name='disability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='loss.DisabilityType', verbose_name='Disability'),
        ),
    ]
