# Generated by Django 2.1.5 on 2019-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0019_auto_20190422_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='status',
            field=models.CharField(choices=[('destroyed', 'Destroyed'), ('affected', 'Affected')], default=None, max_length=25, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
