# Generated by Django 2.1.5 on 2019-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0020_agriculture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='economic_loss',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Economic Loss'),
        ),
    ]
