# Generated by Django 2.1.5 on 2019-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190515_1111'),
        ('loss', '0021_agriculture_economic_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuretype',
            name='owner_organizations',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='organizations', to='organization.Organization'),
        ),
    ]
