# Generated by Django 2.1.5 on 2019-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0022_infrastructuretype_owner_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuretype',
            name='owner_organizations',
            field=models.ManyToManyField(related_name='organizations', to='organization.Organization'),
        ),
    ]
