# Generated by Django 2.1.5 on 2019-02-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='loss',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loss.Loss'),
        ),
    ]
