# Generated by Django 2.1.5 on 2019-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20190226_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reported_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
