# Generated by Django 2.1.5 on 2019-03-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_auto_20190313_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('can_verify', 'Can verify incident')]},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
    ]
