# Generated by Django 2.1.5 on 2019-03-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_auto_20190315_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='hazard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='hazard.Hazard'),
        ),
    ]
