# Generated by Django 2.1.5 on 2019-03-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_auto_20190322_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='files')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='incident.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
