# Generated by Django 2.1.5 on 2019-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='old',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
