# Generated by Django 2.1.5 on 2019-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_auto_20190327_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hazard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='hazard.Hazard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_on',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
