# Generated by Django 2.1.5 on 2019-04-08 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_auto_20190329_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
