# Generated by Django 2.1.5 on 2019-04-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_auto_20190408_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='inducer',
        ),
    ]
