# Generated by Django 2.1.5 on 2019-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_auto_20190411_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsource',
            name='display_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsource',
            name='display_name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
