# Generated by Django 2.1.5 on 2019-04-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0017_auto_20190419_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('can_verify', 'Can verify incident'), ('can_approve', 'Can approve incident'), ('can_edit', 'Can edit incident')], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
    ]
