# Generated by Django 2.1.5 on 2019-04-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0019_incident_need_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('verify_incident', 'Can verify incident'), ('approve_incident', 'Can approve incident'), ('edit_incident', 'Can edit incident')], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
    ]
