# Generated by Django 2.1.5 on 2019-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0020_auto_20190426_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='verification_message',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Verification Message'),
        ),
    ]
