# Generated by Django 2.1.5 on 2019-02-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
