# Generated by Django 2.1.5 on 2019-02-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_auto_20190226_0259'),
        ('federal', '0002_auto_20190221_1151'),
    ]

    operations = [
    ]
