# Generated by Django 2.1.5 on 2019-02-26 16:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_merge_20190226_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='municipality',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='province',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ward',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
