# Generated by Django 2.1.5 on 2019-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0005_municipality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='title_ne',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='title_ne',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='title_ne',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
