# Generated by Django 2.1.5 on 2019-04-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0006_auto_20190412_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='title_ne',
        ),
        migrations.RunSQL(
            sql="UPDATE federal_municipality set title_en=federal_municipality.title;",
            reverse_sql="UPDATE federal_municipality set title_en=null;"
        ),
        migrations.RunSQL(
            sql="UPDATE federal_district set title_en=federal_district.title;",
            reverse_sql="UPDATE federal_district set title_en=null;"
        ),
        migrations.RunSQL(
            sql="UPDATE federal_province set title_en=federal_province.title;",
            reverse_sql="UPDATE federal_province set title_en=null;"
        ),
    ]
