# Generated by Django 2.1.5 on 2019-05-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0007_auto_20190418_0213'),
        ('user', '0002_auto_20190422_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='federal.District', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='municipality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='federal.Municipality', verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='federal.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('municipality', 'Municipality'), ('district', 'District'), ('province', 'Province')], default=None, max_length=25, null=True),
        ),
    ]
