# Generated by Django 2.1.5 on 2019-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190506_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('municipality', 'Municipality'), ('district', 'District'), ('province', 'Province'), ('national', 'National')], default=None, max_length=25, null=True),
        ),
    ]
