# Generated by Django 2.1.5 on 2019-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190510_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opt_email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='opt_sms_notification',
            field=models.BooleanField(default=False),
        ),
    ]
