# Generated by Django 2.1.5 on 2019-03-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20190308_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='federal.Ward'),
        ),
    ]
