# Generated by Django 2.1.5 on 2019-05-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20190311_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('religion', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('opening_hours', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.AddField(
            model_name='education',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='no_of_employee',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='no_of_student',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='opening_hours',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='operator_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='atm_available',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='bank_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='network',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='opening_hours',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='operator_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='place_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='type',
            field=models.CharField(blank=True, choices=[('bureau_de_change', 'Money Exchange'), ('bank', 'Bank'), ('atm', 'ATM')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governance',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='governance',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governance',
            name='type',
            field=models.CharField(blank=True, choices=[('police', 'Police')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='governance',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='ambulance_service',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='emergency_service',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='icu',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='nicu',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='no_of_staffs',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='opening_hours',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='operating_theater',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='operator_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='x_ray',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='classroom_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='channel',
            field=models.CharField(blank=True, choices=[('blb', 'Branchless Banking'), ('branch', 'Branch'), ('atm', 'ATM')], default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='population',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
